export type TopicCategory = "network-systems" | "measurement" | "security" | "emerging" | "infrastructure";

export const TOPICS: { slug: string; category: TopicCategory }[] = [
  { slug: "dc-networking", category: "network-systems" },
  { slug: "transport-protocols", category: "network-systems" },
  { slug: "programmable-net", category: "network-systems" },
  { slug: "sdn-nfv", category: "network-systems" },
  { slug: "congestion-ctrl", category: "network-systems" },
  { slug: "internet-measure", category: "measurement" },
  { slug: "traffic-analysis", category: "measurement" },
  { slug: "dns-bgp", category: "measurement" },
  { slug: "network-monitoring", category: "measurement" },
  { slug: "network-observability", category: "measurement" },
  { slug: "ddos-defense", category: "security" },
  { slug: "protocol-security", category: "security" },
  { slug: "privacy-anonymity", category: "security" },
  { slug: "side-channels", category: "security" },
  { slug: "zero-trust", category: "security" },
  { slug: "sase-sse", category: "security" },
  { slug: "edge-computing", category: "emerging" },
  { slug: "network-ai", category: "emerging" },
  { slug: "machine-learning", category: "emerging" },
  { slug: "optimization", category: "emerging" },
  { slug: "ai-networking", category: "emerging" },
  { slug: "network-digital-twin", category: "emerging" },
  { slug: "intent-based-networking", category: "emerging" },
  { slug: "satellite-leo", category: "emerging" },
  { slug: "quantum-networking", category: "emerging" },
  { slug: "5g-6g", category: "emerging" },
  { slug: "mobile-wireless", category: "emerging" },
  { slug: "ebpf-xdp", category: "infrastructure" },
  { slug: "distributed-sys", category: "infrastructure" },
  { slug: "storage-net", category: "infrastructure" },
  { slug: "os-network-stack", category: "infrastructure" },
  { slug: "cloud-infra", category: "infrastructure" },
  { slug: "hpc", category: "infrastructure" },
  { slug: "high-speed-networking", category: "infrastructure" },
  { slug: "parallel-computing", category: "infrastructure" },
  { slug: "security", category: "security" },
  { slug: "automation", category: "infrastructure" },
  { slug: "observability", category: "measurement" },
];
