DELETE FROM conferences;

INSERT INTO conferences (name, abbreviation, url, location, start_date, end_date, category, tier, topics) VALUES
('Network and Distributed System Security Symposium 2026', 'NDSS', 'https://www.ndss-symposium.org/ndss2026/', 'San Diego, USA', '2026-02-23', '2026-02-27', 'security', 'top', ARRAY['ddos-defense','protocol-security','privacy-anonymity','dns-bgp']),
('ACM European Conference on Computer Systems 2026', 'EuroSys', 'https://2026.eurosys.org/', 'Edinburgh, UK', '2026-04-27', '2026-04-30', 'infrastructure', 'top', ARRAY['distributed-sys','os-network-stack','cloud-infra','ebpf-xdp']),
('USENIX Symposium on Networked Systems Design and Implementation 2026', 'NSDI', 'https://www.usenix.org/conference/nsdi26', 'Renton, USA', '2026-05-04', '2026-05-06', 'network-systems', 'top', ARRAY['dc-networking','transport-protocols','programmable-net','congestion-ctrl']),
('IEEE Symposium on Security and Privacy 2026', 'S&P', 'https://sp2026.ieee-security.org/', 'San Francisco, USA', '2026-05-18', '2026-05-21', 'security', 'top', ARRAY['protocol-security','privacy-anonymity','side-channels','ddos-defense']),
('USENIX Symposium on Operating Systems Design and Implementation 2026', 'OSDI', 'https://www.usenix.org/conference/osdi26', 'Seattle, USA', '2026-07-13', '2026-07-15', 'infrastructure', 'top', ARRAY['distributed-sys','os-network-stack','storage-net','cloud-infra']),
('USENIX Annual Technical Conference 2026', 'ATC', 'https://www.usenix.org/conferences/byname/131', 'Seattle, USA', '2026-07-13', '2026-07-15', 'infrastructure', 'good', ARRAY['distributed-sys','cloud-infra','os-network-stack','ebpf-xdp']),
('USENIX Security Symposium 2026', 'USENIX Security', 'https://www.usenix.org/conference/usenixsecurity26', 'Baltimore, USA', '2026-08-12', '2026-08-14', 'security', 'top', ARRAY['protocol-security','side-channels','privacy-anonymity','ddos-defense']),
('ACM SIGCOMM Conference 2026', 'SIGCOMM', 'https://conferences.sigcomm.org/sigcomm/2026/', 'Denver, USA', '2026-08-17', '2026-08-21', 'network-systems', 'top', ARRAY['dc-networking','transport-protocols','sdn-nfv','congestion-ctrl','programmable-net']),
('ACM Symposium on Operating Systems Principles 2026', 'SOSP', 'https://sigops.org/s/conferences/sosp/2026/', 'Prague, Czechia', '2026-09-29', '2026-10-02', 'infrastructure', 'top', ARRAY['distributed-sys','os-network-stack','storage-net','cloud-infra']),
('ACM Internet Measurement Conference 2026', 'IMC', 'https://conferences.sigcomm.org/imc/2026/', 'Karlsruhe, Germany', '2026-10-12', '2026-10-16', 'measurement', 'top', ARRAY['internet-measure','traffic-analysis','dns-bgp','network-monitoring']),
('ACM Workshop on Hot Topics in Networks 2026', 'HotNets', 'https://www.sigcomm.org/events/hotnets-workshop', 'TBD', '2026-11-01', '2026-11-02', 'network-systems', 'workshop', ARRAY['dc-networking','programmable-net','network-ai','congestion-ctrl']),
('ACM Conference on Computer and Communications Security 2026', 'CCS', 'https://www.sigsac.org/ccs/CCS2026/', 'The Hague, Netherlands', '2026-11-15', '2026-11-19', 'security', 'top', ARRAY['protocol-security','privacy-anonymity','side-channels']),
('ACM Conference on emerging Networking EXperiments and Technologies 2026', 'CoNEXT', 'https://conferences.sigcomm.org/co-next/2026/', 'Utrecht, Netherlands', '2026-12-07', '2026-12-11', 'network-systems', 'good', ARRAY['transport-protocols','edge-computing','network-ai','sdn-nfv']),
('Network and Distributed System Security Symposium 2027', 'NDSS', 'https://www.ndss-symposium.org/ndss2027/', 'Seoul, South Korea', '2027-03-22', '2027-03-26', 'security', 'top', ARRAY['ddos-defense','protocol-security','privacy-anonymity','dns-bgp']),
('ACM European Conference on Computer Systems 2027', 'EuroSys', 'https://2027.eurosys.org/', 'Rabat, Morocco', '2027-04-19', '2027-04-24', 'infrastructure', 'top', ARRAY['distributed-sys','os-network-stack','cloud-infra','ebpf-xdp']),
('USENIX Symposium on Networked Systems Design and Implementation 2027', 'NSDI', 'https://www.usenix.org/conference/nsdi27', 'Providence, USA', '2027-05-11', '2027-05-13', 'network-systems', 'top', ARRAY['dc-networking','transport-protocols','programmable-net','congestion-ctrl']),
('IEEE Symposium on Security and Privacy 2027', 'S&P', 'https://sp2027.ieee-security.org/', 'Montreal, Canada', '2027-05-18', '2027-05-21', 'security', 'top', ARRAY['protocol-security','privacy-anonymity','side-channels','ddos-defense']);
