DO $$
DECLARE cid uuid;
BEGIN
SELECT id INTO cid FROM conferences WHERE abbreviation = 'EuroSys' AND start_date = '2026-04-27';
INSERT INTO conference_sessions (conference_id, title, authors, affiliations, topics, url) VALUES
(cid, 'AdaServe: Accelerating Multi-SLO LLM Serving with Speculative Decoding', ARRAY['Zikun Li','Zhuofu Chen','Remi Delacourt','Gabriele Oliaro','Zeyu Wang','Qinghan Chen','Zhihao Jia'], ARRAY['CMU','Princeton','EPFL'], ARRAY['cloud-infra','distributed-sys'], NULL),
(cid, 'FlexPipe: Adapting Dynamic LLM Serving in Serverless Clusters', ARRAY['Yanying Lin','Shijie Peng','Chengzhi Lu','ChengZhong Xu','Kejiang Ye'], ARRAY['SIAT/CAS','University of Macau'], ARRAY['cloud-infra','distributed-sys'], NULL),
(cid, 'Learn-to-Probe: Signal Distinguishability in Learning-based Congestion Control', ARRAY['Han Tian','Wenbo Li','Junxue Zhang','Xudong Liao','Kai Chen'], ARRAY['HKUST'], ARRAY['congestion-ctrl','transport-protocols'], NULL),
(cid, 'REPS: Recycled Entropy Packet Spraying for Adaptive Load Balancing', ARRAY['Tommaso Bonato','Abdul Kabbani','Ahmad Ghalayini','Torsten Hoefler'], ARRAY['ETH Zurich'], ARRAY['dc-networking','transport-protocols'], NULL),
(cid, 'Handling Network Faults in Distributed AI Training', ARRAY['Xin Zhe Khooi','Zhuo Jiang','Pan Xie','Mun Choon Chan'], ARRAY['NUS','ByteDance'], ARRAY['dc-networking','distributed-sys'], NULL),
(cid, 'MegaScale-MoE: Communication-Efficient Training of MoE Models', ARRAY['Chao Jin','Ziheng Jiang','Zhihao Bai','Xin Jin','Xin Liu'], ARRAY['PKU','ByteDance'], ARRAY['dc-networking','distributed-sys'], NULL),
(cid, 'GeDES: GPU-Driven Discrete Event Network Simulator', ARRAY['Qinyong Li','Zhiwei Zhao','Geyong Min','Zi Wang'], ARRAY['UESTC','University of Exeter'], ARRAY['dc-networking','network-monitoring'], NULL),
(cid, 'TokenFlow: Responsive LLM Streaming via Preemptive Scheduling', ARRAY['Junyi Chen','Chuheng Du','Renyuan Liu','Shuochao Yao'], ARRAY['SJTU','George Mason U'], ARRAY['cloud-infra','distributed-sys'], NULL),
(cid, 'Multipath Collective Communication Beyond Scale-up Networks', ARRAY['Yuchen Xu','Jianglong Nie','Baojia Li','Congcong Miao','Wenfei Wu'], ARRAY['THU','PKU'], ARRAY['dc-networking','transport-protocols'], NULL),
(cid, 'Canopy: Property-Driven Learning for Congestion Control', ARRAY['Chenxi Yang','Divyanshu Saxena','Aditya Akella'], ARRAY['UT Austin'], ARRAY['congestion-ctrl','transport-protocols'], NULL),
(cid, 'SkyWalker: Locality-Aware Cross-Region Load Balancer for LLM', ARRAY['Tian Xia','Ziming Mao','Ion Stoica'], ARRAY['UC Berkeley','Rice'], ARRAY['cloud-infra','dc-networking'], NULL),
(cid, 'Concord: Learning Network Configuration Contracts', ARRAY['Ryan Beckett','Francis Y. Yan','Siva Kesava Reddy Kakarla'], ARRAY['Microsoft Research'], ARRAY['sdn-nfv','network-monitoring'], NULL),
(cid, 'MFS: Efficient Model Family Serving System for LLMs', ARRAY['Yunxuan Zhang','Hao Wang','Han Tian','Kai Chen'], ARRAY['HKUST','USTC'], ARRAY['cloud-infra','distributed-sys'], NULL),
(cid, 'Zeppelin: Balancing Variable-length Workloads in Data Parallel Training', ARRAY['Chang Chen','Tiancheng Chen','Torsten Hoefler'], ARRAY['PKU','ETH Zurich','MIT'], ARRAY['distributed-sys','dc-networking'], NULL),
(cid, 'Efficient Overlapping for Computation and Communication via Signaling', ARRAY['Ke Hong','Xiuhong Li','Guohao Dai','Yu Wang'], ARRAY['THU','PKU'], ARRAY['dc-networking','distributed-sys'], NULL),
(cid, 'KUNSERVE: Parameter-centric Memory Management for LLM Serving', ARRAY['Rongxin Cheng','Yuxin Lai','Xingda Wei','Rong Chen','Haibo Chen'], ARRAY['SJTU'], ARRAY['cloud-infra','os-network-stack'], NULL),
(cid, 'SwitchFS: Async Metadata Updates with In-Network Coordination', ARRAY['Jingwei Xu','Mingkai Dong','Haibo Chen'], ARRAY['SJTU'], ARRAY['storage-net','programmable-net'], NULL),
(cid, 'DROPS: Managing Serverless Resource Pools in Azure Functions', ARRAY['Ahmed Alquraan','Sameh Elnikety','Samer Al-Kiswany'], ARRAY['University of Waterloo','Microsoft'], ARRAY['cloud-infra','distributed-sys'], NULL),
(cid, 'Rearchitecting Programmable Networks For In-Network Computing', ARRAY['Haifeng Sun','Bing Liu','Qun Huang'], ARRAY['THU'], ARRAY['programmable-net','dc-networking'], NULL),
(cid, 'SmartNS: Line-rate Flexible Network Stack with SmartNIC', ARRAY['Xuzheng Chen','Jie Zhang','Zeke Wang'], ARRAY['ZJU','MSRA'], ARRAY['programmable-net','os-network-stack'], NULL),
(cid, 'Enabling Packet Spraying over Commodity RNICs', ARRAY['Xiangzhou Liu','Wenxue Li','Zihao Wang','Kai Chen'], ARRAY['HKUST'], ARRAY['dc-networking','transport-protocols'], NULL),
(cid, 'ECOTE: Priority-Aware Optical Restoration for WAN Traffic Engineering', ARRAY['Yiren Zhao','Kunling He','Congcong Miao'], ARRAY['THU'], ARRAY['dc-networking','sdn-nfv'], NULL),
(cid, 'LCMP: Cost-Aware Multi-Path Routing for Inter-DC RDMA', ARRAY['Dong-Yang Yu','Yuchao Zhang','Wenfei Wu','Ke Xu'], ARRAY['BUPT','THU'], ARRAY['dc-networking','transport-protocols'], NULL),
(cid, 'EMVOD: Elastic Multi-Path QUIC for CDN Video-on-Demand', ARRAY['ZiQi Wei','Qing Li','Yong Jiang'], ARRAY['Peng Cheng Lab','THU'], ARRAY['transport-protocols','edge-computing'], NULL),
(cid, 'Scalable RDMA-accelerated Distributed Locks', ARRAY['Miao Cai','Junru Shen','Rong Gu','Baoliu Ye'], ARRAY['NJU'], ARRAY['dc-networking','distributed-sys'], NULL),
(cid, 'NutCracker: Compilation Framework for Hybrid DPU Architectures', ARRAY['Yihan Yang','Haifeng Sun','Antoine Kaufmann','Jialin Li'], ARRAY['NUS','MPI-SWS'], ARRAY['programmable-net','os-network-stack'], NULL),
(cid, 'Not A DPU in Name Only! RDMA-capable DPUs in Serverless Clouds', ARRAY['Shixiong Qi','K. K. Ramakrishnan','Puneet Sharma'], ARRAY['UC Riverside','HPE'], ARRAY['programmable-net','cloud-infra'], NULL),
(cid, 'Fix: externalizing network I/O in serverless computing', ARRAY['Yuhan Deng','Akshay Srivatsan','Keith Winstein'], ARRAY['Stanford'], ARRAY['os-network-stack','cloud-infra'], NULL),
(cid, 'Reducing GPU Memory Bottleneck with Lossless Compression for ML', ARRAY['Aditya Kamath','Arvind Krishnamurthy','Simon Peter'], ARRAY['U Washington','KAUST'], ARRAY['dc-networking','cloud-infra'], NULL),
(cid, 'RLive: Robust Delivery System for Scaling Live Streaming', ARRAY['Yu Tian','Gerui Lv','Qinghua Wu','Zhenyu Li'], ARRAY['ICT/CAS','Kuaishou'], ARRAY['edge-computing','transport-protocols'], NULL),
(cid, 'Mitigating CDN Cache Misses with Scheduling', ARRAY['Zixuan Yang','Jiaqi Zheng','Guihai Chen'], ARRAY['NJU','ByteDance'], ARRAY['edge-computing','cloud-infra'], NULL),
(cid, 'KRAKENGUARD: Fine-Grained eBPF Isolation', ARRAY['Jainil Patel','Adrien Ghosn','Marios Kogias'], ARRAY['EPFL'], ARRAY['ebpf-xdp','os-network-stack'], NULL),
(cid, 'Practical RDMA Connection Sharing for HPC', ARRAY['Yuejie Wang','Tuo Fang','Guyue Liu'], ARRAY['THU'], ARRAY['dc-networking','transport-protocols'], NULL),
(cid, 'STAlloc: Memory Efficiency in Large Model Training', ARRAY['Zixiao Huang','Junhao Hu','Guohao Dai','Yu Wang'], ARRAY['THU','SJTU'], ARRAY['distributed-sys','cloud-infra'], NULL),
(cid, 'Arena: Dynamic Scheduling and Adaptive Parallelism for Training', ARRAY['Chunyu Xue','Weihao Cui','Quan Chen','Bingsheng He','Minyi Guo'], ARRAY['SJTU','NUS'], ARRAY['distributed-sys','cloud-infra'], NULL),
(cid, 'Laminar: Scalable Asynchronous RL Post-Training Framework', ARRAY['Guangming Sheng','Yuxuan Tong','Borui Wan','Chuan Wu'], ARRAY['HKU','ByteDance'], ARRAY['distributed-sys','cloud-infra'], NULL),
(cid, 'HetAuto: Cross-Cluster Auto-Parallelism for Heterogeneous Training', ARRAY['Guicheng Qi','Junwei Su','Chuan Wu'], ARRAY['HKU','Meituan'], ARRAY['distributed-sys','dc-networking'], NULL),
(cid, 'Digital Hole: Bypassing Commercial Audio DRM', ARRAY['Bjorn Ruytenberg','Herbert Bos','Asia Slowinska'], ARRAY['VU Amsterdam'], ARRAY['protocol-security','side-channels'], NULL),
(cid, 'Five Minutes of DDoS Brings down Tor', ARRAY['Zhongtang Luo','Jianting Zhang','Aniket Kate'], ARRAY['Purdue'], ARRAY['ddos-defense','privacy-anonymity'], NULL),
(cid, 'TrustWeave: Integrity Attestation For Multi-Cloud LLMs', ARRAY['Jianchang Su','Youyou Lu','Wei Zhang'], ARRAY['THU'], ARRAY['cloud-infra','protocol-security'], NULL);
END $$;
