DO $$
DECLARE cid uuid;
BEGIN
SELECT id INTO cid FROM conferences WHERE abbreviation = 'S&P' AND start_date = '2026-05-18';
INSERT INTO conference_sessions (conference_id, title, authors, affiliations, topics, url) VALUES
(cid, 'Heap Localization: Cache Side-Channel based Linux Kernel Heap Exploit Techniques', ARRAY['Yoochan Lee','Sihyun Roh','Hyuk Kwon','Byoungyoung Lee','Thorsten Holz'], ARRAY['Seoul National University','KAIST'], ARRAY['side-channels','os-network-stack'], NULL),
(cid, 'EyeSpy: Inferring Eye Gaze via Side-Channel Attacks Against Foveated Rendering', ARRAY['Paul Maynard','Harris Amjad','Camila Molinares','Bo Ji','Brendan David-John'], ARRAY['Virginia Tech'], ARRAY['side-channels','privacy-anonymity'], NULL),
(cid, 'TDXRay: Microarchitectural Side-Channel Analysis of Intel TDX for Real-World Workloads', ARRAY['Tristan Hornetz','Hosein Yavarzadeh','Albert Cheu','Adria Gascon','Lukas Gerlach','Daniel Moghimi','Phillipp Schoppmann','Michael Schwarz','Ruiyi Zhang'], ARRAY['CISPA Helmholtz Center for Information Security','UC San Diego','Google'], ARRAY['side-channels','cloud-infra'], NULL),
(cid, 'One Tap to Hijack Them All: A Security Analysis of the Google Fast Pair Protocol', ARRAY['Sayon Duttagupta','Seppe Wyns','Nikola Antonijević','Dave Singelée','Bart Preneel'], ARRAY['KU Leuven'], ARRAY['protocol-security'], NULL),
(cid, 'Privacy-Conscious Algorithm Design via PAC Privacy', ARRAY['Mayuri Sridhar','Xiaochen Zhu','Srinivas Devadas'], ARRAY['MIT'], ARRAY['privacy-anonymity'], NULL),
(cid, 'A Leakage-Free Framework for Private Set Operations', ARRAY['Wenhao Wu','Yuyue Chen','Bowen Shen','Peng Yang','Ximing Fu','Zoe Lin Jiang','Junbin Fang'], ARRAY['Jinan University','Harbin Institute of Technology'], ARRAY['privacy-anonymity','protocol-security'], NULL),
(cid, 'The Fault in Our Drafts: Vulnerabilities in RPKI Specification and Software', ARRAY['Oliver Jacobsen','Tobias Kirsch','Haya Schulmann','Niklas Vogel','Michael Waidner'], ARRAY['ATHENE','Goethe-Universität Frankfurt','Fraunhofer SIT','TU Darmstadt'], ARRAY['dns-bgp','protocol-security'], NULL),
(cid, 'Knocking on the Front Door: An LLM-Guided Systematic Analysis of DNS Query Processing Vulnerabilities', ARRAY['Chongrong Li','Pengfei Zhu','Yun Li','Zhanpeng Guo','Jingyu Li','Yuncong Hu','Zhicong Huang','Cheng Hong'], ARRAY['Shanghai Jiao Tong University','Tsinghua University','Ant Group'], ARRAY['dns-bgp','protocol-security','network-ai'], NULL),
(cid, 'Specializing Language Models for Textual Fuzzing via Reinforcement Learning', ARRAY['Jiayi Lin','Liangcai Su','Junzhe Li','Chenxiong Qian'], ARRAY['University of Hong Kong'], ARRAY['protocol-security','machine-learning'], NULL),
(cid, 'Camveil: Unveiling Security Camera Vulnerabilities through Multi-Protocol Coordinated Fuzzing', ARRAY['Fuchen Ma','Yuqiao Yang','Yuanliang Chen','Yanyang Zhao','Ting Chen','Yu Jiang'], ARRAY['Tsinghua University','UESTC'], ARRAY['protocol-security'], NULL),
(cid, 'Jazzer: Coverage-Guided Fuzzing for Semantic Vulnerabilities in the Java Ecosystem', ARRAY['Sergej Dechand','Tobias Wienand','Fabian Meumertzheim','Peter Samarin','Simon Resch','Khaled Yakdan','Thorsten Holz','Flavio Toffalini'], ARRAY['Max Planck Institute for Security and Privacy','Ruhr University Bochum','Code Intelligence'], ARRAY['protocol-security'], NULL),
(cid, 'PUFFERDOS: Efficient and Effective Attack String Generation for Regular Expression Denial of Service Vulnerabilities', ARRAY['Shangzhi Xu','Ziqi Ding','Xiao Cheng','Yuekang Li','Nan Sun','Benjamin Turnbull','Shuangxiang Kan','Siqi Ma'], ARRAY['UNSW','CSIRO','Macquarie University','University of Wollongong'], ARRAY['ddos-defense','protocol-security'], NULL),
(cid, 'Crucible: Retrofitting Commodity CPUs with Vulnerabilities via Transparent Software Emulation', ARRAY['Tristan Hornetz','Lukas Gerlach','Michael Schwarz'], ARRAY['CISPA Helmholtz Center for Information Security'], ARRAY['side-channels'], NULL),
(cid, 'TREVEX: A Black-Box Detection Framework For Data-Flow Transient Execution Vulnerabilities', ARRAY['Daniel Weber','Fabian Thomas','Leon Trampert','Ruiyi Zhang','Michael Schwarz'], ARRAY['CISPA Helmholtz Center for Information Security'], ARRAY['side-channels'], NULL),
(cid, 'SoK: Robustness in Large Language Models against Jailbreak Attacks', ARRAY['Feiyue Xu','Hongsheng Hu','Chaoxiang He','Sheng Hang','Hanqing Hu','Xiuming Liu','Yubo Zhao','Zhengyan Zhou','Bin Benjamin Zhu','Shi-Feng Sun','Dawu Gu','Shuo Wang'], ARRAY['Shanghai Jiao Tong University','Microsoft'], ARRAY['network-ai','machine-learning'], NULL),
(cid, 'Efficient Arithmetic-and-Comparison Homomorphic Encryption with Space Switching', ARRAY[], ARRAY[], ARRAY['privacy-anonymity','protocol-security'], NULL);
END $$;
